In [2]:
import numpy as np 
import pandas as pd

In [4]:
credits = pd.read_csv("contentdata/tmdb_5000_credits.csv")
movies = pd.read_csv("contentdata/tmdb_5000_movies.csv")

credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
print(credits.shape)
print(movies.shape)

(4803, 4)
(4803, 20)

In [7]:
credits = credits.rename(index=str, columns={"movie_id": "id"})
credits.head()

,id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
df_merge = movies.merge(credits, on="id")
df_merge.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
df_cleaned = df_merge.drop(columns=["homepage", "title_x", "title_y", "status", "production_countries"])
df_cleaned.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
df_cleaned.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [11]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   id                    4803 non-null   int64
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   original_title        4803 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   object
 9   release_date          4802 non-null   object
 10  revenue               4803 non-null   int64
 11  runtime               4801 non-null   float64
 12  spoken_languages      4803 non-null   object
 13  tagline               3959 non-null   object
 14  vote_average          4803 non-null   float64
 15  vote_count            4803 non-null   int64
 16  cast                  4803 non-null   object
 17  crew                  4803 non-null   object
dtypes: float64(3), int64(4), object(11)
memory usage: 675.5+ KB

In [12]:
df_cleaned['overview'].head()

0    In the 22nd century, a paraplegic Marine is di...
1    Captain Barbossa, long believed to be dead, ha...
2    A cryptic message from Bond’s past sends him o...
3    Following the death of District Attorney Harve...
4    John Carter is a war-weary, former military ca...
Name: overview, dtype: object

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfv = TfidfVectorizer(
    min_df = 3,
    max_features = None,
    strip_accents = "unicode",
    analyzer = "word",
    token_pattern = r'\w{1,}',
    ngram_range = (1, 3),         # Taking combinations of 1-3 different kind of words
    stop_words = "english"        # Remove the unnecessary stopword characters
)

df_cleaned['overview'] = df_cleaned['overview'].fillna('')   # Removing NaN values

tfv_matrix = tfv.fit_transform(df_cleaned['overview'])   # => Sparse Matrix(vectors) => most of the values in matrix = 0
tfv_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 127220 stored elements and shape (4803, 10417)>

In [14]:
tfv_matrix.shape

(4803, 10417)

In [15]:
from sklearn.metrics.pairwise import sigmoid_kernel
# Sigmoid => Responsible for transforming input between 0 to 1
# Passing the summary vectors in the sigmoid function => Will get values between 0 and 1

sig = sigmoid_kernel(tfv_matrix, tfv_matrix)    # Combination of the same matrix
sig[0]
# Overview 1 related to overview 1, overview 1 related to overview 2, overview 1 related to overview 3, and so on

array([0.76163447, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416], shape=(4803,))

In [16]:
# Mapping of Indices and Corresponding Movie Titles in the dataset
indices = pd.Series(df_cleaned.index, index=df_cleaned['original_title']).drop_duplicates()
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [17]:
# Movie Index for the movie "Shanghai Calling"
print(indices['Shanghai Calling'])
print(sig[4801])

4801
[0.76159416 0.76159416 0.76159416 ... 0.76159483 0.76163447 0.76159461]

In [18]:
# Converting the range of the sigmoid values to a list along with respective indices using the enumerate function
# [(Index, Score)]
list(enumerate(sig[indices['Shanghai Calling']]))

[(0, np.float64(0.7615941559557649)),
 (1, np.float64(0.7615941559557649)),
 (2, np.float64(0.7615941559557649)),
 (3, np.float64(0.7615957266283514)),
 (4, np.float64(0.7615941559557649)),
 (5, np.float64(0.7615943593980157)),
 (6, np.float64(0.7615945340984431)),
 (7, np.float64(0.7615941559557649)),
 (8, np.float64(0.7615953936982669)),
 (9, np.float64(0.761594367248053)),
 (10, np.float64(0.7615941559557649)),
 (11, np.float64(0.7615941559557649)),
 (12, np.float64(0.7615941559557649)),
 (13, np.float64(0.7615941559557649)),
 (14, np.float64(0.7615955938506791)),
 (15, np.float64(0.7615947495664399)),
 (16, np.float64(0.7615941559557649)),
 (17, np.float64(0.7615941559557649)),
 (18, np.float64(0.7615944439688758)),
 (19, np.float64(0.7615950630300182)),
 (20, np.float64(0.7615941559557649)),
 (21, np.float64(0.7615941559557649)),
 (22, np.float64(0.7615941559557649)),
 (23, np.float64(0.7615941559557649)),
 (24, np.float64(0.7615980254629632)),
 (25, np.float64(0.7615943885039911)),
 (26, np.float64(0.7615941559557649)),
 (27, np.float64(0.7615941559557649)),
 (28, np.float64(0.7615941559557649)),
 (29, np.float64(0.7615950590140795)),
 (30, np.float64(0.7615941559557649)),
 (31, np.float64(0.7615941559557649)),
 (32, np.float64(0.7615944342377062)),
 (33, np.float64(0.7615941559557649)),
 (34, np.float64(0.7615941559557649)),
 (35, np.float64(0.7615965027106367)),
 (36, np.float64(0.7615948927771239)),
 (37, np.float64(0.7615947020505157)),
 (38, np.float64(0.7615947277635199)),
 (39, np.float64(0.7615981397077376)),
 (40, np.float64(0.7615941559557649)),
 (41, np.float64(0.761594381504273)),
 (42, np.float64(0.7615941559557649)),
 (43, np.float64(0.7615941559557649)),
 (44, np.float64(0.7615941559557649)),
 (45, np.float64(0.7615941559557649)),
 (46, np.float64(0.7615947316309515)),
 (47, np.float64(0.7615941559557649)),
 (48, np.float64(0.7615941559557649)),
 (49, np.float64(0.7615941559557649)),
 (50, np.float64(0.7615941559557649)),
 (51, np.float64(0.7615945457374683)),
 (52, np.float64(0.761596033032597)),
 (53, np.float64(0.7615941559557649)),
 (54, np.float64(0.7615941559557649)),
 (55, np.float64(0.7615943890761114)),
 (56, np.float64(0.7615944790621074)),
 (57, np.float64(0.7615957059531299)),
 (58, np.float64(0.7615941559557649)),
 (59, np.float64(0.7615951421492401)),
 (60, np.float64(0.7615941559557649)),
 (61, np.float64(0.7615941559557649)),
 (62, np.float64(0.7615941559557649)),
 (63, np.float64(0.7615941559557649)),
 (64, np.float64(0.7615941559557649)),
 (65, np.float64(0.7615952779414936)),
 (66, np.float64(0.7615946938389291)),
 (67, np.float64(0.7615941559557649)),
 (68, np.float64(0.7615941559557649)),
 (69, np.float64(0.7615943643653249)),
 (70, np.float64(0.7615941559557649)),
 (71, np.float64(0.7615948421896255)),
 (72, np.float64(0.7615941559557649)),
 (73, np.float64(0.7615941559557649)),
 (74, np.float64(0.7615941559557649)),
 (75, np.float64(0.7615947571775674)),
 (76, np.float64(0.7615941559557649)),
 (77, np.float64(0.7615950164820237)),
 (78, np.float64(0.7615946071153066)),
 (79, np.float64(0.7615943810649258)),
 (80, np.float64(0.7615941559557649)),
 (81, np.float64(0.7615951623075017)),
 (82, np.float64(0.7615941559557649)),
 (83, np.float64(0.7615947141639552)),
 (84, np.float64(0.7615941559557649)),
 (85, np.float64(0.7615955177188726)),
 (86, np.float64(0.7615948260501574)),
 (87, np.float64(0.7615941559557649)),
 (88, np.float64(0.7615941559557649)),
 (89, np.float64(0.7615943846091794)),
 (90, np.float64(0.7615941559557649)),
 (91, np.float64(0.7615941559557649)),
 (92, np.float64(0.7615941559557649)),
 (93, np.float64(0.7615945289564088)),
 (94, np.float64(0.7615941559557649)),
 (95, np.float64(0.7615941559557649)),
 (96, np.float64(0.7615945516876714)),
 (97, np.float64(0.7615945530661007)),
 (98, np.float64(0.7615941559557649)),
 (99, np.float64(0.761594804820877)),
 (100, np.float64(0.7615941559557649)),
 (101, np.float64(0.7615944345318731)),
 (102, np.float64(0.7615941559557649)),
 (103, np.float64(0.7615941559557649)),
 (104, np.float64(0.7615941559557649)),
 (105, np.float64(0.7615945197510844)),
 (106, np.float64(0.7615941559557649)),
 (107, np.float64(0.7615941559557649)),
 (108, np.float64(0.7615944036635304)),
 (109, np.float64(0.7615941559557649)),
 (110, np.float64(0.7615954988301165)),
 (111, np.float64(0.7615978325131475)),
 (112, np.float64(0.7615941559557649)),
 (113, np.float64(0.7615941559557649)),
 (114, np.float64(0.761594507330811)),
 (115, np.float64(0.7615951243656093)),
 (116, np.float64(0.7615965934760447)),
 (117, np.float64(0.7615941559557649)),
 (118, np.float64(0.7615941559557649)),
 (119, np.float64(0.7615944123780645)),
 (120, np.float64(0.7615952445173924)),
 (121, np.float64(0.761594548475072)),
 (122, np.float64(0.7615941559557649)),
 (123, np.float64(0.7615948977274174)),
 (124, np.float64(0.7615946969540925)),
 (125, np.float64(0.7615943466379338)),
 (126, np.float64(0.7615946036125018)),
 (127, np.float64(0.7615945176398783)),
 (128, np.float64(0.7615941559557649)),
 (129, np.float64(0.7615941559557649)),
 (130, np.float64(0.7615953301108986)),
 (131, np.float64(0.7615946218702324)),
 (132, np.float64(0.761594435126093)),
 (133, np.float64(0.7615941559557649)),
 (134, np.float64(0.7615941559557649)),
 (135, np.float64(0.7615941559557649)),
 (136, np.float64(0.7615961666650806)),
 (137, np.float64(0.7615942837263365)),
 (138, np.float64(0.7615941559557649)),
 (139, np.float64(0.7615946508075723)),
 (140, np.float64(0.761595391610772)),
 (141, np.float64(0.7615941559557649)),
 (142, np.float64(0.7615941559557649)),
 (143, np.float64(0.761594997310149)),
 (144, np.float64(0.7615941559557649)),
 (145, np.float64(0.7615947785196012)),
 (146, np.float64(0.761596084062187)),
 (147, np.float64(0.7615941559557649)),
 (148, np.float64(0.7615941559557649)),
 (149, np.float64(0.7615941559557649)),
 (150, np.float64(0.7615944987223999)),
 (151, np.float64(0.7615941559557649)),
 (152, np.float64(0.7615941559557649)),
 (153, np.float64(0.7615941559557649)),
 (154, np.float64(0.7615941559557649)),
 (155, np.float64(0.7615946066358897)),
 (156, np.float64(0.7615941559557649)),
 (157, np.float64(0.7615941559557649)),
 (158, np.float64(0.7615941559557649)),
 (159, np.float64(0.7615941559557649)),
 (160, np.float64(0.761594718427013)),
 (161, np.float64(0.7615941559557649)),
 (162, np.float64(0.7615941559557649)),
 (163, np.float64(0.7615941559557649)),
 (164, np.float64(0.7615958686992377)),
 (165, np.float64(0.7615941559557649)),
 (166, np.float64(0.7615941559557649)),
 (167, np.float64(0.7615948129075096)),
 (168, np.float64(0.7615946344939761)),
 (169, np.float64(0.7615941559557649)),
 (170, np.float64(0.7615946316502927)),
 (171, np.float64(0.7615941559557649)),
 (172, np.float64(0.7615941559557649)),
 (173, np.float64(0.7615941559557649)),
 (174, np.float64(0.7615944721669327)),
 (175, np.float64(0.7615945323657687)),
 (176, np.float64(0.7615941559557649)),
 (177, np.float64(0.7615941559557649)),
 (178, np.float64(0.761594698969897)),
 (179, np.float64(0.7615941559557649)),
 (180, np.float64(0.7615943757227676)),
 (181, np.float64(0.7615941559557649)),
 (182, np.float64(0.7615951019234395)),
 (183, np.float64(0.7615941559557649)),
 (184, np.float64(0.7615943680140049)),
 (185, np.float64(0.7615944379463636)),
 (186, np.float64(0.7615941559557649)),
 (187, np.float64(0.761598511508911)),
 (188, np.float64(0.7615941559557649)),
 (189, np.float64(0.7615941559557649)),
 (190, np.float64(0.7615947249715836)),
 (191, np.float64(0.7615945532366722)),
 (192, np.float64(0.7615943769079181)),
 (193, np.float64(0.7615945739621567)),
 (194, np.float64(0.7615941559557649)),
 (195, np.float64(0.7615949327704008)),
 (196, np.float64(0.7615945282058976)),
 (197, np.float64(0.7615944794813587)),
 (198, np.float64(0.7615941559557649)),
 (199, np.float64(0.761594895596935)),
 (200, np.float64(0.7615941559557649)),
 (201, np.float64(0.7615941559557649)),
 (202, np.float64(0.7615941559557649)),
 (203, np.float64(0.7615941559557649)),
 (204, np.float64(0.7615946030256021)),
 (205, np.float64(0.7615945060817009)),
 (206, np.float64(0.7615945233371332)),
 (207, np.float64(0.7615941559557649)),
 (208, np.float64(0.7615941559557649)),
 (209, np.float64(0.7615945160202318)),
 (210, np.float64(0.7615943734782511)),
 (211, np.float64(0.761594633564009)),
 (212, np.float64(0.7615958150744744)),
 (213, np.float64(0.7615946943493418)),
 (214, np.float64(0.7615941559557649)),
 (215, np.float64(0.7615951648391858)),
 (216, np.float64(0.7615941559557649)),
 (217, np.float64(0.7615944973352801)),
 (218, np.float64(0.7615941559557649)),
 (219, np.float64(0.7615941559557649)),
 (220, np.float64(0.7615947657902137)),
 (221, np.float64(0.7615941559557649)),
 (222, np.float64(0.7615944931617549)),
 (223, np.float64(0.7615941559557649)),
 (224, np.float64(0.7615941559557649)),
 (225, np.float64(0.7615947166680318)),
 (226, np.float64(0.7615941559557649)),
 (227, np.float64(0.7615941559557649)),
 (228, np.float64(0.7615946612322892)),
 (229, np.float64(0.7615944719244819)),
 (230, np.float64(0.7615943833133939)),
 (231, np.float64(0.7615941559557649)),
 (232, np.float64(0.7615941559557649)),
 (233, np.float64(0.7615941559557649)),
 (234, np.float64(0.7615944210387919)),
 (235, np.float64(0.7615945512460784)),
 (236, np.float64(0.7615941559557649)),
 (237, np.float64(0.7615941559557649)),
 (238, np.float64(0.7615954286650398)),
 (239, np.float64(0.7615941559557649)),
 (240, np.float64(0.761595178469382)),
 (241, np.float64(0.7615943959452826)),
 (242, np.float64(0.7615958278496144)),
 (243, np.float64(0.7615941559557649)),
 (244, np.float64(0.7615941559557649)),
 (245, np.float64(0.7615947825101443)),
 (246, np.float64(0.7615947680063461)),
 (247, np.float64(0.761594566039359)),
 (248, np.float64(0.7615941559557649)),
 (249, np.float64(0.7615941559557649)),
 (250, np.float64(0.7615941559557649)),
 (251, np.float64(0.7615960986020633)),
 (252, np.float64(0.7615941559557649)),
 (253, np.float64(0.7615943332646056)),
 (254, np.float64(0.7615946664255309)),
 (255, np.float64(0.761594599662688)),
 (256, np.float64(0.7615941559557649)),
 (257, np.float64(0.7615941559557649)),
 (258, np.float64(0.7615943619846005)),
 (259, np.float64(0.7615944644533372)),
 (260, np.float64(0.7615941559557649)),
 (261, np.float64(0.7615941559557649)),
 (262, np.float64(0.7615941559557649)),
 (263, np.float64(0.7615941559557649)),
 (264, np.float64(0.7615945420277151)),
 (265, np.float64(0.7615941559557649)),
 (266, np.float64(0.7615941559557649)),
 (267, np.float64(0.7615941559557649)),
 (268, np.float64(0.7615941559557649)),
 (269, np.float64(0.7615941559557649)),
 (270, np.float64(0.7615941559557649)),
 (271, np.float64(0.7615941559557649)),
 (272, np.float64(0.7615954999476832)),
 (273, np.float64(0.7615949103744766)),
 (274, np.float64(0.7615941559557649)),
 (275, np.float64(0.7615941559557649)),
 (276, np.float64(0.7615941559557649)),
 (277, np.float64(0.7615949517812631)),
 (278, np.float64(0.7615941559557649)),
 (279, np.float64(0.761594585157129)),
 (280, np.float64(0.7615941559557649)),
 (281, np.float64(0.7615941559557649)),
 (282, np.float64(0.7615948556610413)),
 (283, np.float64(0.7615954939725268)),
 (284, np.float64(0.7615945531856708)),
 (285, np.float64(0.76159506161451)),
 (286, np.float64(0.7615949893338536)),
 (287, np.float64(0.761594678058899)),
 (288, np.float64(0.7615947853421547)),
 (289, np.float64(0.7615947700507878)),
 (290, np.float64(0.7615949288631596)),
 (291, np.float64(0.7615941559557649)),
 (292, np.float64(0.7615941559557649)),
 (293, np.float64(0.7615941559557649)),
 (294, np.float64(0.7615946939044015)),
 (295, np.float64(0.7615962376226633)),
 (296, np.float64(0.7615964978867397)),
 (297, np.float64(0.7615941559557649)),
 (298, np.float64(0.7615966311137738)),
 (299, np.float64(0.761595079526535)),
 (300, np.float64(0.7615947876259216)),
 (301, np.float64(0.7615946866002757)),
 (302, np.float64(0.7615944065476594)),
 (303, np.float64(0.7615943800398538)),
 (304, np.float64(0.7615944366941554)),
 (305, np.float64(0.7615941559557649)),
 (306, np.float64(0.7615952691417316)),
 (307, np.float64(0.7615951476450662)),
 (308, np.float64(0.7615941559557649)),
 (309, np.float64(0.7615961437686055)),
 (310, np.float64(0.7615943206201147)),
 (311, np.float64(0.7615946394526996)),
 (312, np.float64(0.7615941559557649)),
 (313, np.float64(0.7615941559557649)),
 (314, np.float64(0.7615941559557649)),
 (315, np.float64(0.761594744753692)),
 (316, np.float64(0.7615943565763433)),
 (317, np.float64(0.7615941559557649)),
 (318, np.float64(0.7615946800160631)),
 (319, np.float64(0.7615941559557649)),
 (320, np.float64(0.7615941559557649)),
 (321, np.float64(0.7615941559557649)),
 (322, np.float64(0.7615941559557649)),
 (323, np.float64(0.7615941559557649)),
 (324, np.float64(0.7615948933265256)),
 (325, np.float64(0.7615944495114491)),
 (326, np.float64(0.7615941559557649)),
 (327, np.float64(0.7615945711555728)),
 (328, np.float64(0.7615941559557649)),
 (329, np.float64(0.7615968145689285)),
 (330, np.float64(0.7615967161799637)),
 (331, np.float64(0.7615941559557649)),
 (332, np.float64(0.7615941559557649)),
 (333, np.float64(0.7615941559557649)),
 (334, np.float64(0.761594366965648)),
 (335, np.float64(0.7615941559557649)),
 (336, np.float64(0.7615941559557649)),
 (337, np.float64(0.7615944776586107)),
 (338, np.float64(0.7615941559557649)),
 (339, np.float64(0.7615953986816232)),
 (340, np.float64(0.7615947180377524)),
 (341, np.float64(0.7615944050985463)),
 (342, np.float64(0.7615945019047825)),
 (343, np.float64(0.7615941559557649)),
 (344, np.float64(0.7615941559557649)),
 (345, np.float64(0.7615941559557649)),
 (346, np.float64(0.7615954488848354)),
 (347, np.float64(0.7615947098811024)),
 (348, np.float64(0.7615944452232908)),
 (349, np.float64(0.7615941559557649)),
 (350, np.float64(0.7615941559557649)),
 (351, np.float64(0.7615948293042815)),
 (352, np.float64(0.7615977269557336)),
 (353, np.float64(0.7615941559557649)),
 (354, np.float64(0.7615950164755262)),
 (355, np.float64(0.7615952386910524)),
 (356, np.float64(0.761594501972099)),
 (357, np.float64(0.7615941559557649)),
 (358, np.float64(0.7615941559557649)),
 (359, np.float64(0.7615960337249)),
 (360, np.float64(0.7615941559557649)),
 (361, np.float64(0.7615941559557649)),
 (362, np.float64(0.7615955833713335)),
 (363, np.float64(0.7615941559557649)),
 (364, np.float64(0.7615941559557649)),
 (365, np.float64(0.7615941559557649)),
 (366, np.float64(0.7615941559557649)),
 (367, np.float64(0.7615950332906207)),
 (368, np.float64(0.7615941559557649)),
 (369, np.float64(0.7615941559557649)),
 (370, np.float64(0.7615944606870152)),
 (371, np.float64(0.7615941559557649)),
 (372, np.float64(0.7615948149392036)),
 (373, np.float64(0.7615941559557649)),
 (374, np.float64(0.7615945221010261)),
 (375, np.float64(0.7615943407024454)),
 (376, np.float64(0.7615941559557649)),
 (377, np.float64(0.7615954356363606)),
 (378, np.float64(0.7615947682889237)),
 (379, np.float64(0.7615944003993137)),
 (380, np.float64(0.7615941559557649)),
 (381, np.float64(0.7615941559557649)),
 (382, np.float64(0.7615941559557649)),
 (383, np.float64(0.7615941559557649)),
 (384, np.float64(0.7615941559557649)),
 (385, np.float64(0.7615941559557649)),
 (386, np.float64(0.7615941559557649)),
 (387, np.float64(0.7615941559557649)),
 (388, np.float64(0.7615941559557649)),
 (389, np.float64(0.7615948575807111)),
 (390, np.float64(0.7615949038245543)),
 (391, np.float64(0.761595323420986)),
 (392, np.float64(0.7615941559557649)),
 (393, np.float64(0.761594391976295)),
 (394, np.float64(0.7615953374994433)),
 (395, np.float64(0.7615956701779838)),
 (396, np.float64(0.7615941559557649)),
 (397, np.float64(0.7615962550243328)),
 (398, np.float64(0.7615944621483686)),
 (399, np.float64(0.7615941559557649)),
 (400, np.float64(0.7615941559557649)),
 (401, np.float64(0.7615941559557649)),
 (402, np.float64(0.7615941559557649)),
 (403, np.float64(0.7615948108896495)),
 (404, np.float64(0.7615941559557649)),
 (405, np.float64(0.7615941559557649)),
 (406, np.float64(0.7615941559557649)),
 (407, np.float64(0.7615941559557649)),
 (408, np.float64(0.7615941559557649)),
 (409, np.float64(0.7615941559557649)),
 (410, np.float64(0.7615950357062056)),
 (411, np.float64(0.7615944190396887)),
 (412, np.float64(0.7615941559557649)),
 (413, np.float64(0.7615961069199396)),
 (414, np.float64(0.7615941559557649)),
 (415, np.float64(0.7615943092098338)),
 (416, np.float64(0.7615941559557649)),
 (417, np.float64(0.7615941559557649)),
 (418, np.float64(0.7615941559557649)),
 (419, np.float64(0.7615941559557649)),
 (420, np.float64(0.7615941559557649)),
 (421, np.float64(0.7615941559557649)),
 (422, np.float64(0.7615960855149894)),
 (423, np.float64(0.7615952011619401)),
 (424, np.float64(0.7615952086103267)),
 (425, np.float64(0.7615949029879913)),
 (426, np.float64(0.7615941559557649)),
 (427, np.float64(0.7615941559557649)),
 (428, np.float64(0.7615944666315604)),
 (429, np.float64(0.7615944920177898)),
 (430, np.float64(0.7615943860291297)),
 (431, np.float64(0.7615956586591968)),
 (432, np.float64(0.7615945644320589)),
 (433, np.float64(0.7615941559557649)),
 (434, np.float64(0.7615945533514193)),
 (435, np.float64(0.7615953173606662)),
 (436, np.float64(0.7615943769755343)),
 (437, np.float64(0.7615955332693031)),
 (438, np.float64(0.7615941559557649)),
 (439, np.float64(0.7615941559557649)),
 (440, np.float64(0.7615941559557649)),
 (441, np.float64(0.7615941559557649)),
 (442, np.float64(0.7615941559557649)),
 (443, np.float64(0.7615941559557649)),
 (444, np.float64(0.7615945723853613)),
 (445, np.float64(0.761596187853401)),
 (446, np.float64(0.7615946109878898)),
 (447, np.float64(0.7615941559557649)),
 (448, np.float64(0.7615950421616547)),
 (449, np.float64(0.7615941559557649)),
 (450, np.float64(0.7615957365820382)),
 (451, np.float64(0.7615941559557649)),
 (452, np.float64(0.7615941559557649)),
 (453, np.float64(0.7615957150608944)),
 (454, np.float64(0.7615941559557649)),
 (455, np.float64(0.7615948069968811)),
 (456, np.float64(0.7615941559557649)),
 (457, np.float64(0.7615941559557649)),
 (458, np.float64(0.7615956734537475)),
 (459, np.float64(0.761594744272789)),
 (460, np.float64(0.7615948010917527)),
 (461, np.float64(0.7615941559557649)),
 (462, np.float64(0.7615944431778072)),
 (463, np.float64(0.7615941559557649)),
 (464, np.float64(0.7615957354190548)),
 (465, np.float64(0.7615945000688197)),
 (466, np.float64(0.7615941559557649)),
 (467, np.float64(0.7615941559557649)),
 (468, np.float64(0.7615941559557649)),
 (469, np.float64(0.7615945156655124)),
 (470, np.float64(0.7615941559557649)),
 (471, np.float64(0.7615941559557649)),
 (472, np.float64(0.7615941559557649)),
 (473, np.float64(0.7615941559557649)),
 (474, np.float64(0.7615945624064594)),
 (475, np.float64(0.7615953249437145)),
 (476, np.float64(0.7615941559557649)),
 (477, np.float64(0.7615941559557649)),
 (478, np.float64(0.7615943449023491)),
 (479, np.float64(0.7615941559557649)),
 (480, np.float64(0.7615946221192205)),
 (481, np.float64(0.7615941559557649)),
 (482, np.float64(0.7615941559557649)),
 (483, np.float64(0.7615941559557649)),
 (484, np.float64(0.7615941559557649)),
 (485, np.float64(0.7615946763973642)),
 (486, np.float64(0.7615945274039887)),
 (487, np.float64(0.7615949440098806)),
 (488, np.float64(0.7615951542573253)),
 (489, np.float64(0.7615965937025787)),
 (490, np.float64(0.7615952099322026)),
 (491, np.float64(0.7615953894027123)),
 (492, np.float64(0.7615941559557649)),
 (493, np.float64(0.7615946991462613)),
 (494, np.float64(0.7615941559557649)),
 (495, np.float64(0.7615941559557649)),
 (496, np.float64(0.7615945117588523)),
 (497, np.float64(0.7615948453282808)),
 (498, np.float64(0.7615941559557649)),
 (499, np.float64(0.7615947324147707)),
 (500, np.float64(0.7615941559557649)),
 (501, np.float64(0.7615941559557649)),
 (502, np.float64(0.7615941559557649)),

In [19]:
sorted(list(enumerate(sig[indices['Shanghai Calling']])), key=lambda x: x[1], reverse=True)

[(4801, np.float64(0.7616344692549826)),
 (2027, np.float64(0.7616003968173323)),
 (1369, np.float64(0.7615994856175351)),
 (1949, np.float64(0.7615992707132185)),
 (1480, np.float64(0.761599257449354)),
 (1796, np.float64(0.7615989494069652)),
 (2573, np.float64(0.7615989004520236)),
 (3371, np.float64(0.7615985442684898)),
 (187, np.float64(0.761598511508911)),
 (3437, np.float64(0.7615984756871621)),
 (4752, np.float64(0.7615984267816296)),
 (2017, np.float64(0.7615982514413332)),
 (39, np.float64(0.7615981397077376)),
 (24, np.float64(0.7615980254629632)),
 (4646, np.float64(0.7615978759213945)),
 (3624, np.float64(0.7615978543338763)),
 (2890, np.float64(0.7615978338627732)),
 (111, np.float64(0.7615978325131475)),
 (2452, np.float64(0.7615978230608309)),
 (352, np.float64(0.7615977269557336)),
 (4241, np.float64(0.7615976348700638)),
 (549, np.float64(0.7615975794864329)),
 (3397, np.float64(0.7615975696895556)),
 (1944, np.float64(0.7615974877578744)),
 (4466, np.float64(0.7615974627345858)),
 (3047, np.float64(0.7615974116748351)),
 (2494, np.float64(0.7615974054133006)),
 (3872, np.float64(0.7615974027151584)),
 (3839, np.float64(0.7615973968489351)),
 (1626, np.float64(0.7615973556494884)),
 (2507, np.float64(0.7615973296910733)),
 (3779, np.float64(0.7615972123852901)),
 (2382, np.float64(0.7615971876413112)),
 (2038, np.float64(0.7615971733862413)),
 (4586, np.float64(0.761597153174053)),
 (1133, np.float64(0.7615971455995928)),
 (2281, np.float64(0.7615971390304603)),
 (3599, np.float64(0.7615971280707502)),
 (1642, np.float64(0.7615971226662246)),
 (826, np.float64(0.7615970616581152)),
 (2217, np.float64(0.761596986923892)),
 (4747, np.float64(0.7615969773898038)),
 (2761, np.float64(0.7615969546060433)),
 (3895, np.float64(0.7615969374551692)),
 (2447, np.float64(0.7615969232496582)),
 (3674, np.float64(0.7615968999304976)),
 (1238, np.float64(0.7615968956925772)),
 (1215, np.float64(0.7615968724982737)),
 (3154, np.float64(0.7615968698866176)),
 (710, np.float64(0.7615968675372282)),
 (1728, np.float64(0.7615968644115673)),
 (329, np.float64(0.7615968145689285)),
 (3010, np.float64(0.7615967980127036)),
 (2945, np.float64(0.7615967947458415)),
 (1212, np.float64(0.7615967917603236)),
 (2792, np.float64(0.7615967814716292)),
 (1675, np.float64(0.7615967755020943)),
 (1300, np.float64(0.7615967648451769)),
 (330, np.float64(0.7615967161799637)),
 (1366, np.float64(0.7615967154003005)),
 (2600, np.float64(0.7615966928045615)),
 (3935, np.float64(0.7615966613907427)),
 (2605, np.float64(0.7615966343922956)),
 (298, np.float64(0.7615966311137738)),
 (929, np.float64(0.7615966094006978)),
 (4430, np.float64(0.761596603528895)),
 (4749, np.float64(0.761596599339543)),
 (489, np.float64(0.7615965937025787)),
 (116, np.float64(0.7615965934760447)),
 (2783, np.float64(0.7615965864086701)),
 (2352, np.float64(0.7615965813447281)),
 (3739, np.float64(0.7615965404926941)),
 (883, np.float64(0.7615965392956727)),
 (4714, np.float64(0.7615965179328223)),
 (3937, np.float64(0.761596515258579)),
 (1335, np.float64(0.7615965057028348)),
 (35, np.float64(0.7615965027106367)),
 (930, np.float64(0.761596502520545)),
 (2183, np.float64(0.7615965013138933)),
 (296, np.float64(0.7615964978867397)),
 (4429, np.float64(0.7615964972751478)),
 (3118, np.float64(0.7615964905225414)),
 (1237, np.float64(0.7615964801260472)),
 (2500, np.float64(0.7615964780759971)),
 (4472, np.float64(0.761596476929343)),
 (1515, np.float64(0.7615964766318285)),
 (1384, np.float64(0.7615964708018649)),
 (1067, np.float64(0.761596470406837)),
 (530, np.float64(0.7615964703702148)),
 (2399, np.float64(0.7615964673858946)),
 (3975, np.float64(0.7615964529673404)),
 (1880, np.float64(0.7615964432184547)),
 (3246, np.float64(0.7615964429478994)),
 (2935, np.float64(0.7615964315110825)),
 (2177, np.float64(0.7615964307132306)),
 (2246, np.float64(0.7615964302227106)),
 (3487, np.float64(0.7615964287610516)),
 (3062, np.float64(0.7615964249133207)),
 (3591, np.float64(0.761596413496208)),
 (2626, np.float64(0.7615964117124349)),
 (4194, np.float64(0.7615964069077981)),
 (4206, np.float64(0.7615963996256341)),
 (1099, np.float64(0.7615963995908062)),
 (2960, np.float64(0.7615963941655085)),
 (629, np.float64(0.7615963900529426)),
 (3554, np.float64(0.761596378758152)),
 (4126, np.float64(0.761596373333693)),
 (1499, np.float64(0.7615963648413596)),
 (4225, np.float64(0.761596347501806)),
 (3256, np.float64(0.7615963466913704)),
 (987, np.float64(0.7615963394740256)),
 (4351, np.float64(0.7615963367547576)),
 (993, np.float64(0.7615963363500424)),
 (975, np.float64(0.7615963109865752)),
 (2431, np.float64(0.7615963070646482)),
 (4016, np.float64(0.7615963032892504)),
 (3117, np.float64(0.7615962984295307)),
 (4355, np.float64(0.7615962857388038)),
 (3052, np.float64(0.7615962845231677)),
 (1092, np.float64(0.7615962775701901)),
 (2870, np.float64(0.7615962726210049)),
 (2669, np.float64(0.7615962700256917)),
 (4284, np.float64(0.7615962698545642)),
 (2265, np.float64(0.7615962553802957)),
 (397, np.float64(0.7615962550243328)),
 (4519, np.float64(0.761596254656185)),
 (3144, np.float64(0.7615962478356052)),
 (2279, np.float64(0.7615962391123461)),
 (295, np.float64(0.7615962376226633)),
 (1181, np.float64(0.7615962254567971)),
 (2145, np.float64(0.7615962226217823)),
 (1161, np.float64(0.7615962162269362)),
 (896, np.float64(0.7615961964229774)),
 (445, np.float64(0.761596187853401)),
 (3309, np.float64(0.7615961735469011)),
 (4448, np.float64(0.761596171886469)),
 (136, np.float64(0.7615961666650806)),
 (3837, np.float64(0.7615961481961939)),
 (309, np.float64(0.7615961437686055)),
 (1232, np.float64(0.7615961434498957)),
 (2347, np.float64(0.7615961425134686)),
 (2104, np.float64(0.7615961408327422)),
 (4675, np.float64(0.7615961400137047)),
 (3304, np.float64(0.7615961368402101)),
 (4715, np.float64(0.7615961358159408)),
 (1798, np.float64(0.7615961331035638)),
 (2662, np.float64(0.7615961193629223)),
 (1526, np.float64(0.7615961186193062)),
 (2036, np.float64(0.7615961155484741)),
 (413, np.float64(0.7615961069199396)),
 (3846, np.float64(0.7615961022050561)),
 (4139, np.float64(0.7615960991543124)),
 (251, np.float64(0.7615960986020633)),
 (4129, np.float64(0.7615960929234876)),
 (422, np.float64(0.7615960855149894)),
 (146, np.float64(0.761596084062187)),
 (3069, np.float64(0.7615960808745081)),
 (1580, np.float64(0.7615960604288576)),
 (1060, np.float64(0.7615960585877405)),
 (4569, np.float64(0.761596051829471)),
 (1904, np.float64(0.7615960421275216)),
 (1250, np.float64(0.7615960391344695)),
 (3188, np.float64(0.7615960359788101)),
 (359, np.float64(0.7615960337249)),
 (52, np.float64(0.761596033032597)),
 (2034, np.float64(0.7615960251526307)),
 (1102, np.float64(0.7615960167076351)),
 (763, np.float64(0.7615960150451123)),
 (4099, np.float64(0.7615960109383696)),
 (3704, np.float64(0.761596001610464)),
 (948, np.float64(0.7615960004075311)),
 (703, np.float64(0.7615959865859934)),
 (615, np.float64(0.7615959859638497)),
 (1893, np.float64(0.7615959784822994)),
 (1382, np.float64(0.7615959757154278)),
 (1253, np.float64(0.7615959715166506)),
 (4337, np.float64(0.7615959676217504)),
 (2506, np.float64(0.7615959656843835)),
 (934, np.float64(0.7615959608315205)),
 (1180, np.float64(0.7615959524887932)),
 (955, np.float64(0.7615959522075337)),
 (3238, np.float64(0.7615959477895353)),
 (4755, np.float64(0.7615959452355349)),
 (1941, np.float64(0.7615959412016058)),
 (521, np.float64(0.761595937087567)),
 (1906, np.float64(0.7615959313490255)),
 (1055, np.float64(0.761595926404847)),
 (2744, np.float64(0.761595924321485)),
 (3967, np.float64(0.7615959218108476)),
 (2197, np.float64(0.7615959211460057)),
 (3451, np.float64(0.7615959110687444)),
 (2596, np.float64(0.7615959088973802)),
 (3927, np.float64(0.7615959081813906)),
 (1418, np.float64(0.7615959061357328)),
 (2285, np.float64(0.7615959055049168)),
 (3170, np.float64(0.7615959034738434)),
 (4487, np.float64(0.7615958966391957)),
 (1601, np.float64(0.761595896508759)),
 (4770, np.float64(0.761595892149881)),
 (3592, np.float64(0.7615958916928282)),
 (3243, np.float64(0.7615958894379802)),
 (2713, np.float64(0.761595885363402)),
 (1523, np.float64(0.7615958830629072)),
 (3915, np.float64(0.7615958790608516)),
 (2580, np.float64(0.7615958770819315)),
 (164, np.float64(0.7615958686992377)),
 (1488, np.float64(0.7615958658092855)),
 (4526, np.float64(0.7615958636338306)),
 (590, np.float64(0.7615958607047725)),
 (984, np.float64(0.7615958606480248)),
 (2780, np.float64(0.7615958493443665)),
 (1544, np.float64(0.7615958485908613)),
 (555, np.float64(0.7615958452958386)),
 (242, np.float64(0.7615958278496144)),
 (2396, np.float64(0.7615958249086751)),
 (4353, np.float64(0.7615958235063568)),
 (1739, np.float64(0.7615958232911302)),
 (1817, np.float64(0.761595822159227)),
 (212, np.float64(0.7615958150744744)),
 (893, np.float64(0.7615958142307626)),
 (4403, np.float64(0.7615958127633891)),
 (3348, np.float64(0.7615958035774475)),
 (3670, np.float64(0.7615957982073163)),
 (3395, np.float64(0.7615957950489962)),
 (3972, np.float64(0.761595787987298)),
 (3606, np.float64(0.761595787350725)),
 (1846, np.float64(0.7615957857231594)),
 (3823, np.float64(0.7615957758123533)),
 (2818, np.float64(0.7615957748302833)),
 (3673, np.float64(0.761595773796455)),
 (3566, np.float64(0.7615957733962716)),
 (3186, np.float64(0.7615957711973647)),
 (3257, np.float64(0.7615957704215993)),
 (1664, np.float64(0.761595765966822)),
 (2301, np.float64(0.7615957653010453)),
 (726, np.float64(0.7615957636325089)),
 (560, np.float64(0.7615957605919765)),
 (1220, np.float64(0.7615957597943098)),
 (3654, np.float64(0.76159575883289)),
 (1700, np.float64(0.7615957549886696)),
 (4780, np.float64(0.7615957516068583)),
 (2685, np.float64(0.7615957444534479)),
 (2455, np.float64(0.7615957442442292)),
 (1481, np.float64(0.761595740965824)),
 (3699, np.float64(0.7615957396527745)),
 (1592, np.float64(0.7615957374952282)),
 (450, np.float64(0.7615957365820382)),
 (464, np.float64(0.7615957354190548)),
 (2674, np.float64(0.7615957348806104)),
 (4385, np.float64(0.7615957339888692)),
 (1462, np.float64(0.76159572854081)),
 (3, np.float64(0.7615957266283514)),
 (1236, np.float64(0.7615957235330499)),
 (453, np.float64(0.7615957150608944)),
 (2203, np.float64(0.7615957135286063)),
 (3791, np.float64(0.7615957130544294)),
 (1360, np.float64(0.7615957097661354)),
 (4673, np.float64(0.7615957081822095)),
 (57, np.float64(0.7615957059531299)),
 (1637, np.float64(0.7615957057749132)),
 (2560, np.float64(0.7615957044143493)),
 (1037, np.float64(0.7615957042285284)),
 (1824, np.float64(0.761595703776053)),
 (4645, np.float64(0.7615956993255197)),
 (1323, np.float64(0.7615956970877258)),
 (3173, np.float64(0.7615956945015055)),
 (2894, np.float64(0.7615956897172964)),
 (3934, np.float64(0.761595687145305)),
 (721, np.float64(0.7615956842158453)),
 (3505, np.float64(0.7615956828339308)),
 (3489, np.float64(0.7615956791521156)),
 (3104, np.float64(0.761595677888603)),
 (4417, np.float64(0.7615956777583018)),
 (3319, np.float64(0.761595676617881)),
 (458, np.float64(0.7615956734537475)),
 (1089, np.float64(0.7615956715627428)),
 (395, np.float64(0.7615956701779838)),
 (2274, np.float64(0.7615956671652521)),
 (3317, np.float64(0.7615956651781036)),
 (1275, np.float64(0.7615956620548939)),
 (2314, np.float64(0.7615956607875868)),
 (2801, np.float64(0.7615956607699267)),
 (2621, np.float64(0.761595659863979)),
 (431, np.float64(0.7615956586591968)),
 (913, np.float64(0.7615956583941121)),
 (536, np.float64(0.7615956565940322)),
 (4740, np.float64(0.7615956564189474)),
 (1467, np.float64(0.761595649739178)),
 (2459, np.float64(0.7615956495319702)),
 (4122, np.float64(0.761595647246944)),
 (3997, np.float64(0.7615956465958045)),
 (3011, np.float64(0.7615956447362037)),
 (4252, np.float64(0.7615956399747827)),
 (4224, np.float64(0.7615956397512668)),
 (909, np.float64(0.761595639625038)),
 (797, np.float64(0.7615956379261423)),
 (2490, np.float64(0.7615956353862637)),
 (2994, np.float64(0.7615956315232375)),
 (991, np.float64(0.761595628909178)),
 (867, np.float64(0.7615956268914332)),
 (879, np.float64(0.7615956243986898)),
 (4142, np.float64(0.7615956239069703)),
 (891, np.float64(0.761595619071512)),
 (1548, np.float64(0.7615956172861367)),
 (706, np.float64(0.7615956168084985)),
 (3347, np.float64(0.7615956126683251)),
 (2245, np.float64(0.761595608421299)),
 (1897, np.float64(0.7615956078187492)),
 (1838, np.float64(0.761595600540982)),
 (4259, np.float64(0.7615955942330467)),
 (14, np.float64(0.7615955938506791)),
 (4470, np.float64(0.7615955937785358)),
 (3877, np.float64(0.7615955936906772)),
 (1887, np.float64(0.7615955936874699)),
 (900, np.float64(0.7615955883369977)),
 (4174, np.float64(0.7615955869246097)),
 (906, np.float64(0.76159558649459)),
 (4315, np.float64(0.7615955850330764)),
 (362, np.float64(0.7615955833713335)),
 (3023, np.float64(0.761595583136923)),
 (2695, np.float64(0.7615955830142419)),
 (1584, np.float64(0.7615955793972641)),
 (1477, np.float64(0.7615955769813298)),
 (1851, np.float64(0.7615955680105259)),
 (2365, np.float64(0.7615955654907429)),
 (1685, np.float64(0.7615955646398221)),
 (3541, np.float64(0.7615955644610629)),
 (510, np.float64(0.7615955629780874)),
 (1614, np.float64(0.7615955629674481)),
 (2350, np.float64(0.7615955606478293)),
 (3701, np.float64(0.7615955587841622)),
 (1240, np.float64(0.7615955586478893)),
 (584, np.float64(0.7615955507683565)),
 (2335, np.float64(0.7615955500437653)),
 (1994, np.float64(0.761595549422486)),
 (3664, np.float64(0.7615955482955065)),
 (1983, np.float64(0.7615955480986671)),
 (1046, np.float64(0.7615955463859452)),
 (3859, np.float64(0.7615955451071684)),
 (4700, np.float64(0.7615955434448003)),
 (574, np.float64(0.7615955399059512)),
 (3086, np.float64(0.7615955373923825)),
 (4150, np.float64(0.7615955373508808)),
 (1416, np.float64(0.7615955358973039)),
 (1516, np.float64(0.7615955335229839)),
 (4659, np.float64(0.7615955333586086)),
 (437, np.float64(0.7615955332693031)),
 (2559, np.float64(0.7615955309075897)),
 (3323, np.float64(0.7615955285401445)),
 (724, np.float64(0.7615955284466096)),
 (1697, np.float64(0.7615955265525279)),
 (1299, np.float64(0.7615955227730844)),
 (3745, np.float64(0.7615955183063355)),
 (85, np.float64(0.7615955177188726)),
 (902, np.float64(0.7615955128800895)),
 (1109, np.float64(0.7615955128781269)),
 (3821, np.float64(0.7615955127460182)),
 (1732, np.float64(0.7615955103883713)),
 (967, np.float64(0.761595509915001)),
 (1521, np.float64(0.7615955094328994)),
 (4671, np.float64(0.7615955073392954)),
 (4007, np.float64(0.761595506744715)),
 (3447, np.float64(0.76159550650452)),
 (2260, np.float64(0.7615955046728666)),
 (824, np.float64(0.7615955046411912)),
 (4517, np.float64(0.7615955031860637)),
 (1757, np.float64(0.761595500572263)),
 (4060, np.float64(0.7615955000013109)),
 (272, np.float64(0.7615954999476832)),
 (110, np.float64(0.7615954988301165)),
 (1899, np.float64(0.7615954978947369)),
 (2086, np.float64(0.7615954977593934)),
 (2924, np.float64(0.761595495411683)),
 (3008, np.float64(0.7615954939727011)),
 (283, np.float64(0.7615954939725268)),
 (1520, np.float64(0.7615954937193006)),
 (769, np.float64(0.7615954918569493)),
 (1209, np.float64(0.7615954899447306)),
 (4271, np.float64(0.7615954894597251)),
 (962, np.float64(0.7615954873686067)),
 (3491, np.float64(0.7615954863378364)),
 (1287, np.float64(0.7615954831742101)),
 (2597, np.float64(0.7615954786537388)),
 (4716, np.float64(0.7615954767254924)),
 (3576, np.float64(0.7615954720692402)),
 (761, np.float64(0.7615954715618387)),
 (807, np.float64(0.7615954691469553)),
 (2254, np.float64(0.76159546683657)),
 (4610, np.float64(0.7615954655475947)),
 (1117, np.float64(0.7615954589887614)),
 (588, np.float64(0.7615954561850362)),
 (880, np.float64(0.7615954527911956)),
 (3331, np.float64(0.7615954523969786)),
 (3526, np.float64(0.7615954519301944)),
 (2193, np.float64(0.7615954506719514)),
 (3909, np.float64(0.761595449972014)),
 (346, np.float64(0.7615954488848354)),
 (1083, np.float64(0.7615954447121556)),
 (2649, np.float64(0.7615954444289635)),
 (1624, np.float64(0.7615954437531398)),
 (1669, np.float64(0.7615954428689854)),
 (3174, np.float64(0.761595438437115)),
 (377, np.float64(0.7615954356363606)),
 (3669, np.float64(0.7615954348693194)),
 (4378, np.float64(0.7615954347039264)),
 (3142, np.float64(0.7615954345722911)),
 (4293, np.float64(0.7615954341582631)),
 (3547, np.float64(0.7615954329988968)),
 (2224, np.float64(0.761595429849997)),
 (3261, np.float64(0.7615954296072058)),
 (238, np.float64(0.7615954286650398)),
 (2186, np.float64(0.7615954200699965)),
 (2579, np.float64(0.761595416067455)),
 (1193, np.float64(0.761595415070466)),
 (4338, np.float64(0.761595413546409)),
 (2612, np.float64(0.7615954109567045)),
 (905, np.float64(0.761595403183211)),
 (506, np.float64(0.761595401963142)),
 (2240, np.float64(0.7615953997725421)),
 (1815, np.float64(0.7615953995237634)),
 (339, np.float64(0.7615953986816232)),
 (3504, np.float64(0.7615953954226473)),
 (1398, np.float64(0.7615953952729004)),
 (1162, np.float64(0.7615953939459701)),
 (595, np.float64(0.7615953938540854)),
 (3073, np.float64(0.7615953937882264)),
 (8, np.float64(0.7615953936982669)),
 (3166, np.float64(0.7615953933592282)),
 (3191, np.float64(0.7615953931959482)),
 (3714, np.float64(0.7615953920470415)),
 (140, np.float64(0.761595391610772)),
 (2072, np.float64(0.7615953899407089)),
 (3788, np.float64(0.7615953898920399)),
 (491, np.float64(0.7615953894027123)),
 (2616, np.float64(0.7615953892098112)),
 (3633, np.float64(0.7615953880399174)),
 (3361, np.float64(0.7615953862229499)),
 (3662, np.float64(0.7615953839801011)),
 (3760, np.float64(0.7615953819903664)),
 (4419, np.float64(0.7615953816757886)),
 (2881, np.float64(0.7615953808339051)),
 (523, np.float64(0.7615953796464002)),
 (2874, np.float64(0.7615953777812832)),
 (3396, np.float64(0.7615953740065061)),
 (2721, np.float64(0.7615953733659319)),
 (4635, np.float64(0.761595370656602)),
 (3874, np.float64(0.7615953702837169)),
 (1878, np.float64(0.761595369239434)),
 (2863, np.float64(0.7615953670866626)),
 (1589, np.float64(0.7615953620457109)),
 (2485, np.float64(0.7615953608910835)),
 (2479, np.float64(0.7615953599140753)),
 (779, np.float64(0.7615953580454914)),
 (4394, np.float64(0.7615953579974921)),
 (785, np.float64(0.7615953578617897)),
 (3020, np.float64(0.7615953562693203)),
 (4421, np.float64(0.7615953562068225)),
 (1150, np.float64(0.7615953548966112)),
 (3772, np.float64(0.7615953521655876)),
 (2633, np.float64(0.7615953508785376)),
 (3450, np.float64(0.7615953480765396)),
 (4106, np.float64(0.7615953468311903)),
 (2976, np.float64(0.7615953458843622)),
 (4534, np.float64(0.7615953445850503)),
 (1244, np.float64(0.761595342980486)),
 (1216, np.float64(0.7615953428309061)),
 (4154, np.float64(0.7615953426498271)),
 (1612, np.float64(0.7615953411272286)),
 (658, np.float64(0.7615953411076416)),
 (4666, np.float64(0.7615953410275381)),
 (2901, np.float64(0.7615953408009162)),
 (4196, np.float64(0.7615953399360162)),
 (2788, np.float64(0.7615953384533746)),
 (394, np.float64(0.7615953374994433)),
 (3639, np.float64(0.7615953365363626)),
 (3441, np.float64(0.7615953346956493)),
 (851, np.float64(0.7615953339766997)),
 (3775, np.float64(0.7615953335556486)),
 (1217, np.float64(0.761595332175441)),
 (1795, np.float64(0.7615953317639712)),
 (1258, np.float64(0.7615953314132976)),
 (1393, np.float64(0.7615953313624589)),
 (130, np.float64(0.7615953301108986)),
 (475, np.float64(0.7615953249437145)),
 (391, np.float64(0.761595323420986)),
 (1780, np.float64(0.7615953232776888)),
 (4589, np.float64(0.7615953214739454)),
 (3906, np.float64(0.7615953197863263)),
 (4495, np.float64(0.7615953184269019)),
 (1043, np.float64(0.7615953182991655)),
 (435, np.float64(0.7615953173606662)),
 (2364, np.float64(0.7615953149028658)),

In [20]:
# Give movie title as input and based on the movie title we apply the object created in the sigmoid kernal
# Doing the same thing as above but putting it in the fuction
def give_recommendation(title, sig=sig):
    idx = indices[title]
    sig_scores = list(enumerate(sig[idx]))
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    
    # Getting Top 10 scores(index, scores)
    sig_scores = sig_scores[1:11]
    movie_indices = [i[0] for i in sig_scores]
    return df_cleaned['original_title'].iloc[movie_indices]

In [21]:
give_recommendation('Shanghai Calling')

2027             I Am Sam
1369            Cape Fear
1949           Love Ranch
1480    Big Momma's House
1796             Brothers
2573       Nowhere to Run
3371    Who's Your Caddy?
187         Puss in Boots
3437              Tracker
4752       Tiny Furniture
Name: original_title, dtype: object

In [22]:
give_recommendation('Avatar')

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
942                 The Book of Life
Name: original_title, dtype: object